### ISSUE TITLE
how to group in vertical sections

### ISSUE THREAD

**Issue by lachnerd** [cloudogu/reveal.js-docker-example#5]
How can i group content in vertical sections with markdown files ? 
All i got is one big horizontal presentation.

**Comment by schnatterer** [comment]
Three completely empty lines will separate vertically.

https://github.com/cloudogu/reveal.js-docker-example/blob/cf2be04756e64a2b32e239e9ced7ff9077f12011/docs/slides/01-intro.md#bellow-separated-by-three-empty-lines

In hindsight this could have been solved more intuitively, but keeping compatibility is also a thing.

![image](https://github.com/cloudogu/reveal.js-docker-example/assets/1824962/023fad88-7198-4a35-917f-3f600373e08c)
